baseURL = 'https://leo3391.github.io/blog/'
languageCode = 'en-us'
title = "Leo's Blog"

theme = 're-terminal'
[params]
  themeColor = "green"
  favicon = "favicon.ico"
  name = "Leo"
  email = 'leo3391@proton.me'

[author]
  name = "Leo"
  email = 'leo3391@proton.me'
